import localFont from "next/font/local";
import { Merriweather } from 'next/font/google';
import "./globals.css";

const funnelDisplay = Merriweather({
  subsets: ['latin'],
  variable: '--font-funnel-display',
  weight: "400"
})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "StudyMate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${funnelDisplay.variable} antialiased font-FunnelDisplay`}
      >
        {children}
      </body>
    </html>
  );
}
